Dialogos= {};
Dialogos["Hi Jim"]= [
	"You: Hello?",
	"Jim: Hi, Jim from the frontend team here.",
	"You: Hi Jim! How can I help you?", 
	"Jim: I need to speak with Laura, is she there?",
	"You: I'm afraid she's not here.",
	"You: Do you want to leave a message?",
	"Jim: Yes, we need more information about the cart feature, we are blocked.",
	"You: I'm sending her a text message to her mobile so she knows you called.",
	"Jim: Thanks, bye.",
	"You: Bye.",
];
Dialogos["Hi Nick"]= [
	"Mary: Hello?",
  "Nicholas: Nicholas speaking",
	"Mary: Hi Nicholas, can I speak with John?",
	"Nicholas: Can I tell him who's calling?", 
	"Mary: Yes, it's Mary Johnson",
	"Nicholas: OK, I'm not sure if he's here. Please let me check",
	"Nicholas: I'm afraid he's not here, he's in the sales department.",
	"Mary: Could you please tell me the phone number of that deparment?",
 	"Nicholas: Right. I'll ask and send you an email. Could you please confirm?",
	"Mary: Yes, sure. My email is mary@mybusiness.com",
	"Nicholas: Thanks, bye.",
	"Mary: Bye.",
];
Dialogos["Standup Time"]= [
	"Charles: It's stand-up time.",
	"Charles: Everybody good to go?",
	"Ryoko: Yes",
	"Charles: Okay, Who wants to start?",
	"Harold: I want to",
	"Charles: Great, the floor is yours.",
	"Harold: Yesterday I finished the source code for the recipe request voice interface, and I run a unit test so, that's done.",
	"Harold: Today I'm working on passing the request parameters to the recipe search code.",
	"Harold: My main impediment is still my lack of knowledge of the speech recognition engine.",
	"Harold: Ryoko is our expert, and has been a wonderful help",
	"Harold: But with the time difference it's just challenging.",
	"Charles: Okay. That's very good Harold, but we need to resolve that.",
	"Charles: Ryoko, can you send your schedule?",
	"Charles: I will look into getting travel approval.",
	"Ryoko: Ok, I'll do that.",
	"Charles: Thanks Ryoko.",
	"Charles: Why don't you go next?",
	"Ryoko: Okay sure. Today I...",
];
